### PR TITLE
Updates ExpandVolume API with RDFG

### PR DESCRIPTION
**Pull request by delldubey**
# Description
Adds RDFG number in Expand Volume API

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| https://github.com/dell/csm/issues/336|

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [x] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [x] Did you run tests in a real Kubernetes cluster?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
 - Unit Test:
 411 scenarios (411 passed)
2826 steps (2826 passed)
31.602062832s
testing: warning: no tests to run
PASS
  - Cluster Test

### CODE REVIEW

**Review by shanmydell — APPROVED** [review]
LGTM

**Review by boyamurthy — COMMENTED** [review]
Please fix the vetting error .

inttest/pmax_integration_test.go:1498:97: not enough arguments in call to client.ExpandVolume

**Comment by delldubey** [comment]
> Please fix the vetting error.
> 
> inttest/pmax_integration_test.go:1498:97: not enough arguments in call to client.ExpandVolume

Done!

**Review by boyamurthy — DISMISSED** [review]
LGTM.

**Review by nidtara — DISMISSED** [review]
lgtm!

**Pull request merged**
