### PR TITLE
Implement the Snapshot Policy APIs

### PR DESCRIPTION
**Pull request by nikitajoshi1**
- Add Get ,Create, Update, Delete and Get All APIs for Snapshot Policy

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| https://github.com/dell/csm/issues/770 |

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [x] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [x] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Have you maintained at least 90% code coverage?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
**Integration Tests:**
test_int

**Unit Tests:**
unit_tests

**Linting:**
lint

### CODE REVIEW

**Review by tssushma — CHANGES_REQUESTED** [review]
Could you please recheck the code once. I ran the test and the test are getting failed with the following error.
interface.go:368:55: interface method parameter snapshotPolicyId should be snapshotPolicyID
interface.go:372:58: interface method parameter snapshotPolicyId should be snapshotPolicyID
interface.go:374:58: interface method parameter snapshotPolicyId should be snapshotPolicyID
interface.go:377:73: interface method parameter snapshotPolicyId should be snapshotPolicyID
replication.go:1:1: package comment should be of the form "Package pmax ..."
replication.go:30:71: method parameter snapshotPolicyId should be snapshotPolicyID
replication.go:62:74: method parameter snapshotPolicyId should be snapshotPolicyID
replication.go:80:74: method parameter snapshotPolicyId should be snapshotPolicyID
replication.go:124:89: method parameter snapshotPolicyId should be snapshotPolicyID
types/v100/snapshot_policy.go:1:1: package comment should be of the form "Package v100 ..."
types/v100/snapshot_policy.go:18:6: exported type SnapshotPolicy should have comment or be unexported
types/v100/snapshot_policy.go:49:6: exported type CreateSnapshotPolicyParam should have comment or be unexported
types/v100/snapshot_policy.go:68:6: exported type CloudSnapshotPolicyDetails should have comment or be unexported
types/v100/snapshot_policy.go:75:6: exported type LocalSnapshotPolicyDetails should have comment or be unexported
types/v100/snapshot_policy.go:81:6: exported type ModifySnapshotPolicyParam should have comment or be unexported
types/v100/snapshot_policy.go:96:6: exported type AssociateStorageGroupParam should have comment or be unexported
types/v100/snapshot_policy.go:101:6: exported type DisassociateStorageGroupParam should have comment or be unexported
types/v100/snapshot_policy.go:106:6: exported type UpdateSnapshotPolicyParam should have comment or be unexported

**Comment by nikitajoshi1** [comment]
> Could you please recheck the code once. I ran the test and the test are getting failed with the following error. interface.go:368:55: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:372:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:374:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:377:73: interface method parameter snapshotPolicyId should be snapshotPolicyID replication.go:1:1: package comment should be of the form "Package pmax ..." replication.go:30:71: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:62:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:80:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:124:89: method parameter snapshotPolicyId should be snapshotPolicyID types/v100/snapshot_policy.go:1:1: package comment should be of the form "Package v100 ..." types/v100/snapshot_policy.go:18:6: exported type SnapshotPolicy should have comment or be unexported types/v100/snapshot_policy.go:49:6: exported type CreateSnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:68:6: exported type CloudSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:75:6: exported type LocalSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:81:6: exported type ModifySnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:96:6: exported type AssociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:101:6: exported type DisassociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:106:6: exported type UpdateSnapshotPolicyParam should have comment or be unexported

@tssushma Made updates based on the errors you were seeing. Can you please check and review again?

**Comment by tssushma** [comment]
> > Could you please recheck the code once. I ran the test and the test are getting failed with the following error. interface.go:368:55: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:372:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:374:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:377:73: interface method parameter snapshotPolicyId should be snapshotPolicyID replication.go:1:1: package comment should be of the form "Package pmax ..." replication.go:30:71: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:62:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:80:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:124:89: method parameter snapshotPolicyId should be snapshotPolicyID types/v100/snapshot_policy.go:1:1: package comment should be of the form "Package v100 ..." types/v100/snapshot_policy.go:18:6: exported type SnapshotPolicy should have comment or be unexported types/v100/snapshot_policy.go:49:6: exported type CreateSnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:68:6: exported type CloudSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:75:6: exported type LocalSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:81:6: exported type ModifySnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:96:6: exported type AssociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:101:6: exported type DisassociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:106:6: exported type UpdateSnapshotPolicyParam should have comment or be unexported
> 
> @tssushma Made updates based on the errors you were seeing. Can you please check and review again? Thanks!

@nikitajoshi1 I tested again but few more errors are still there. 
Could you please check it once. And please share the unit test and integration tests results.
 
+ golint -set_exit_status ./...
types/v100/snapshot_policy.go:51:1: comment on exported type CreateSnapshotPolicyParam should be of the form "CreateSnapshotPolicyParam ..." (with optional leading article)
types/v100/snapshot_policy.go:71:1: comment on exported type CloudSnapshotPolicyDetails should be of the form "CloudSnapshotPolicyDetails ..." (with optional leading article)
types/v100/snapshot_policy.go:79:1: comment on exported type LocalSnapshotPolicyDetails should be of the form "LocalSnapshotPolicyDetails ..." (with optional leading article)
types/v100/snapshot_policy.go:87:1: comment on exported type ModifySnapshotPolicyParam should be of the form "ModifySnapshotPolicyParam ..." (with optional leading article)
types/v100/snapshot_policy.go:105:1: comment on exported type AssociateStorageGroupParam should be of the form "AssociateStorageGroupParam ..." (with optional leading article)
types/v100/snapshot_policy.go:111:1: comment on exported type DisassociateStorageGroupParam should be of the form "DisassociateStorageGroupParam ..." (with optional leading article)
types/v100/snapshot_policy.go:117:1: comment on exported type UpdateSnapshotPolicyParam should be of the form "UpdateSnapshotPolicyParam ..." (with optional leading article)
Found 7 lint suggestions; failing.

**Comment by nikitajoshi1** [comment]
> > > Could you please recheck the code once. I ran the test and the test are getting failed with the following error. interface.go:368:55: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:372:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:374:58: interface method parameter snapshotPolicyId should be snapshotPolicyID interface.go:377:73: interface method parameter snapshotPolicyId should be snapshotPolicyID replication.go:1:1: package comment should be of the form "Package pmax ..." replication.go:30:71: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:62:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:80:74: method parameter snapshotPolicyId should be snapshotPolicyID replication.go:124:89: method parameter snapshotPolicyId should be snapshotPolicyID types/v100/snapshot_policy.go:1:1: package comment should be of the form "Package v100 ..." types/v100/snapshot_policy.go:18:6: exported type SnapshotPolicy should have comment or be unexported types/v100/snapshot_policy.go:49:6: exported type CreateSnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:68:6: exported type CloudSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:75:6: exported type LocalSnapshotPolicyDetails should have comment or be unexported types/v100/snapshot_policy.go:81:6: exported type ModifySnapshotPolicyParam should have comment or be unexported types/v100/snapshot_policy.go:96:6: exported type AssociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:101:6: exported type DisassociateStorageGroupParam should have comment or be unexported types/v100/snapshot_policy.go:106:6: exported type UpdateSnapshotPolicyParam should have comment or be unexported
> > 
> > 
> > @tssushma Made updates based on the errors you were seeing. Can you please check and review again? Thanks!
> 
> @nikitajoshi1 I tested again but few more errors are still there. Could you please check it once. And please share the unit test and integration tests results.
> 
> * golint -set_exit_status ./...
>   types/v100/snapshot_policy.go:51:1: comment on exported type CreateSnapshotPolicyParam should be of the form "CreateSnapshotPolicyParam ..." (with optional leading article)
>   types/v100/snapshot_policy.go:71:1: comment on exported type CloudSnapshotPolicyDetails should be of the form "CloudSnapshotPolicyDetails ..." (with optional leading article)
>   types/v100/snapshot_policy.go:79:1: comment on exported type LocalSnapshotPolicyDetails should be of the form "LocalSnapshotPolicyDetails ..." (with optional leading article)
>   types/v100/snapshot_policy.go:87:1: comment on exported type ModifySnapshotPolicyParam should be of the form "ModifySnapshotPolicyParam ..." (with optional leading article)
>   types/v100/snapshot_policy.go:105:1: comment on exported type AssociateStorageGroupParam should be of the form "AssociateStorageGroupParam ..." (with optional leading article)
>   types/v100/snapshot_policy.go:111:1: comment on exported type DisassociateStorageGroupParam should be of the form "DisassociateStorageGroupParam ..." (with optional leading article)
>   types/v100/snapshot_policy.go:117:1: comment on exported type UpdateSnapshotPolicyParam should be of the form "UpdateSnapshotPolicyParam ..." (with optional leading article)
>   Found 7 lint suggestions; failing.

@tssushma Thanks for pointing out the lint errors. Resolved those.

 
lint
Tests:
getsp
listsp
deletesp
addsp
removesp
updatesp

**Comment by nikitajoshi1** [comment]
@tssushma I have made updates for the Unit and Integration tests, could you please review again now? Thanks!

**Review by shanmydell — APPROVED** [review]

**Review by shanmydell — DISMISSED** [review]

**Comment by tssushma** [comment]
> @tssushma I have made updates for the Unit and Integration tests, could you please review again now? Thanks!

I checked on it, the unit test coverage for the has come down from 83.1 to 81.7.

**Comment by nikitajoshi1** [comment]
> > @tssushma I have made updates for the Unit and Integration tests, could you please review again now? Thanks!
> 
> I checked on it, the unit test coverage has come down from 83.1 to 81.7. Few tests are not covered could you please check it.

@tssushma Added few more tests. Coverage 83.3%.
unit_tests
lint

**Review by tssushma — APPROVED** [review]
@nikitajoshi1 thank you for doing the change and covering all the unit test scenarios.
Unit test coverage:

569 scenarios (569 passed)
3765 steps (3765 passed)
35.7178198s
testing: warning: no tests to run
PASS
coverage: 83.3% of statements
status 0
ok      command-line-arguments  35.796s coverage: 83.3% of statements [no tests to run]

**Review by boyamurthy — APPROVED** [review]
LGTM.

**Pull request merged**
