### PR TITLE
Adding executionOption to EditPortGroup payload in UpdatePortGroup API

### PR DESCRIPTION
**Pull request by SoorajBharadwaj07**
# Description
Adding executionOption to EditPortGroup payload in UpdatePortGroup API

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| (https://github.com/dell/csm/issues/441) |
| |

# Checklist:

- [x] Have you run format,vet & lint checks against your submission?
- [x] Have you made sure that the code compiles?
- [x] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [x] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Have you maintained at least 90% code coverage?
- [x] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

### CODE REVIEW

**Comment by SoorajBharadwaj07** [comment]
Attaching the screenshots of unittests and integration test results
gopowermax_units
gopowermax_inttest

**Review by shanmydell — CHANGES_REQUESTED** [review]
Please add the unit tests for the tests added

**Comment by SoorajBharadwaj07** [comment]
> Please add the unit tests for the tests added

Tests for UpdatePortGroup are already available here,
https://github.com/dell/gopowermax/blob/main/unittest/pmax.feature#L684.

There is no change required in these testcases as the change is only to add ExecutionOption in payload.

**Review by tssushma — APPROVED** [review]
LGTM

**Review by shanmydell — APPROVED** [review]

**Pull request merged**
