### PR TITLE
Updating golang version to 1.20

### PR DESCRIPTION
**Pull request by boyamurthy**
Updating golang version to 1.20

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
|https://github.com/dell/csm/issues/658  |

# Checklist:

- [X] Have you run format,vet & lint checks against your submission?
- [X] Have you made sure that the code compiles?
- [X] Did you run the unit & integration tests successfully?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Have you commented your code, particularly in hard-to-understand areas
- [ ] Have you done corresponding changes to the documentation
- [ ] Did you run tests in a real Kubernetes cluster?
- [ ] Have you maintained at least 90% code coverage?
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

unit test

image

### CODE REVIEW

**Review by nidtara — APPROVED** [review]
lgtm!

**Review by santhoshhs10 — DISMISSED** [review]

**Comment by shanmydell** [comment]
@boyamurthy : Pls check gosec issue

**Comment by boyamurthy** [comment]
Unit and integration tests worked fine  . 
https://vmax-jenkins01.cec.lab.emc.com/job/AUTOMATED_CI/job/CSI-PowerMax/job/KAV-gopowermax/254/console

**Review by shanmydell — APPROVED** [review]

**Review by delldubey — APPROVED** [review]
lgtm

**Pull request merged**
